#can be implement with more classic way...vault or even base 64 encryptrion 
apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
type: Opaque
stringData:
    MONGOURI: "mongodb+srv://avia:avshi1212!!@climacelltest-p0maf.gcp.mongodb.net/devops-exercise?retryWrites=true&w=majority"
    